/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun funcion (a: Int, b: Int, c: Int) {
    println ("$ax²+$bx+$c")
}
    

fun main() {
    val a = 2
    val b = 10
    val c = 20
    if (a == 0) {
        println ("a tiene que ser diferente a 0")
    }
    funcion(a,b,c)
}
